controller:
  motion_law_parameters:
    max_velocity: [ 0.5, 0.5, 0.5 ]
    max_acceleration: [ 0.1, 0.1, 0.1 ]

  cascade_controllers: # posso anche filtrare, es su github (guardare)
  - name: "joint1"
    inner:
      Kp: 58.61
      Ki: 1.0
      Kd: 0.0
      filters_on_measure:
        - type: NotchFilter
          natural_frequency: 546.0
          zeros_damping: 0.2
          poles_damping: 0.8
    outer:
      Kp: 5.0
      Ki: 0.0
      Kd: 0.0
  - name: "joint2"
    inner:
      Kp: 40.59
      Ki: 1.0
      Kd: 0.0
      filters_on_measure:
        - type: NotchFilter
          natural_frequency: 662.0
          zeros_damping: 0.2
          poles_damping: 0.8 
    outer:
      Kp: 5.0
      Ki: 0.0
      Kd: 0.0
  - name: "joint3"
    inner:
      Kp: 18.88
      Ki: 1.0
      Kd: 0.0
      filters_on_measure:
        - type: NotchFilter
          natural_frequency: 800.0
          zeros_damping: 0.2
          poles_damping: 0.8
    outer:
      Kp: 15.0
      Ki: 0.0
      Kd: 0.0

model_parameters: # parametri dinamici del robot (es: massa, attriti...)
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0




