controller:
  motion_law_parameters:
    max_velocity: [  150, 150, 150 ]
    max_acceleration: [ 45, 45, 50 ]


  cascade_controllers: # posso anche filtrare, es su github (guardare)
  - name: "joint1"
    inner:
      Kp: 276.2685 #274.9
      Ki: 14.2946
      Kd: 0.0
      filters_on_measure:
        - type: NotchFilter
          natural_frequency: 546.0
          zeros_damping: 0.1
          poles_damping: 0.8
    outer:
      Kp: 27.6
      Ki: 0.0
      Kd: 0.0
  - name: "joint2"
    inner:
      Kp: 231.15
      Ki: 0.025
      Kd: 0.0
      filters_on_measure:
        - type: NotchFilter
          natural_frequency: 662.0
          zeros_damping: 0.2
          poles_damping: 0.8 
    outer:
      Kp: 23.1
      Ki: 0.0
      Kd: 0.0
  - name: "joint3"
    inner:
      Kp: 181.8721 #180.49
      Ki: 3.8096 #3053.98
      Kd: 0.0
      filters_on_measure:
        - type: NotchFilter
          natural_frequency: 783.0
          zeros_damping: 0.1
          poles_damping: 0.8
    outer:
      Kp: 18.1
      Ki: 0.0
      Kd: 0.0

model_parameters: # parametri dinamici del robot (es: massa, attriti...)
- 0.942584
- -0.000000
- 0.000000
- 0.000000
- -0.000000
- -0.000000
- -0.000000
- 0.000000
- 0.000000
- 0.000000
- 1.024973
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.943809
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.100895
- 0.407321
- 0.166951
- -0.286947
- -0.470637
- -0.589369

